apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-puc-tcc-api
spec:
  replicas: 1
  selector:
    matchLabels:
        app: pos.puc.tcc.api 
  template:
    metadata:
      labels:
        app: pos.puc.tcc.api
    spec:
      containers:
      - name: webapi
        image: andrecanuto/pos.puc.tcc.api:latest
        ports:
        - containerPort: 80
        # env:
        # - name: ASPNETCORE_URLS
        #   value: http://*:8080         

---

apiVersion: v1
kind: Service
metadata:
  name: pos-puc-tcc-api
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
     app: pos-puc-tcc-api   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 31500