apiVersion: v1
kind: Service
metadata:
  name: pos-puc-tcc-api
spec:
  type: NodePort
  selector:
     app: pos-puc-tcc-api   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31500